# Usar una imagen base de OpenJDK
FROM openjdk:11-jre-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo WAR a la imagen
COPY target/EscuelaAhuac-1.war /app/EscuelaAhuac-1.war

# Exponer el puerto en el que correrá la aplicación
EXPOSE 8080

# Comando para ejecutar la aplicación Java (WAR)
CMD ["java", "-jar", "EscuelaAhuac-1.war"]
